<?php

declare(strict_types=1);

namespace Pnlx\Attribute;

use Attribute;

/** Marks a class, method, or function as machine-generated by the pnl toolchain. */
#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD | Attribute::TARGET_FUNCTION)]
final class AutoGeneratedByPnlx
{
}
