<?php

declare(strict_types=1);

namespace Pnlx\Attribute;

use Attribute;

/** Marks a class or method as machine-generated by the pnl toolchain. */
#[Attribute(Attribute::TARGET_CLASS | Attribute::TARGET_METHOD)]
final class AutoGeneratedByPnlx
{
}
