<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

use Pnlx\Exception\ExtensionLoadException;
use Pnlx\ManifestInterface;
use Pnlx\Runtime;
use Pnlx\RuntimeInterface;

class ExampleManifest implements ManifestInterface
{
    private readonly RuntimeInterface $runtime;

    /**
     * @param RuntimeInterface|null $runtime Optional runtime; when omitted the
     *     manifest instantiates its own, so callers can simply `new ExampleManifest()`.
     */
    public function __construct(?RuntimeInterface $runtime = null)
    {
        $this->runtime = $runtime ?? new Runtime();
    }

    public function name(): string
    {
        return $this->manifest()['name'];
    }

    public function version(): string
    {
        return $this->manifest()['version'];
    }

    public function hash(): string
    {
        return $this->native()['sha256'];
    }

    public function description(): string
    {
        return $this->manifest()['description'];
    }

    public function path(): string
    {
        return $this->absolutePath($this->native()['library']);
    }

    /**
     * @return array<string, mixed>
     */
    protected function manifest(): array
    {
        return $this->runtime->manifest(Example::class);
    }

    /**
     * @return array{source?: string, library: string, sha256: string}
     */
    protected function native(): array
    {
        $native = $this->runtime->pathmap()['requires']['example'] ?? null;
        if (!is_array($native)) {
            throw new ExtensionLoadException('Native library example is not installed.');
        }

        $libraryKey = isset($native['library']) ? 'library' : 'path';
        foreach ([$libraryKey, 'sha256'] as $key) {
            if (!isset($native[$key]) || !is_string($native[$key]) || $native[$key] === '') {
                throw new ExtensionLoadException(sprintf('Native library example is missing %s.', $key));
            }
        }

        if ($libraryKey === 'path') {
            $native['library'] = $native['path'];
        }

        return $native;
    }

    protected function absolutePath(string $path): string
    {
        if (str_starts_with($path, '/')) {
            return $path;
        }

        return $this->runtime->projectRoot() . '/' . $path;
    }
}
