<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

use Pnlx\Exception\ExtensionLoadException;
use Pnlx\FFI\NativeLibrary;
use Pnlx\RuntimeInterface;

class Example
{
    protected NativeLibrary $native;

    protected RuntimeInterface $runtime;

    protected ExampleContext $context;

    public function __construct(RuntimeInterface $runtime)
    {
        $this->runtime = $runtime;
        $context = $runtime->context(self::class);
        if (!$context instanceof ExampleContext) {
            throw new ExtensionLoadException(sprintf(
                'Extension context for %s must be an instance of %s.',
                self::class,
                ExampleContext::class
            ));
        }
        $this->context = $context;

        if (!is_file($this->context->path())) {
            throw new ExtensionLoadException('an extension cannot be loaded');
        }

        $this->native = $runtime->native(self::class, 'example.ffi.php');
    }

    public function __call(string $name, array $arguments): mixed
    {
        return $this->native->call($name, $arguments);
    }

    public function ExampleVersion(): string
    {
        return \Pnlx\Util::cString($this->__call('ExampleVersion', func_get_args()));
    }

    public function example_version(): string
    {
        return \Pnlx\Util::cString($this->__call('example_version', func_get_args()));
    }

    public function ExampleAdd(int $left, int $right): int
    {
        return (int) $this->__call('ExampleAdd', func_get_args());
    }

    public function example_add(int $left, int $right): int
    {
        return (int) $this->__call('example_add', func_get_args());
    }


}
