// !!! DO NOT EDIT THIS FILE !!!
//
// This file was generated automatically by a machine, so any changes you make to
// it may be overwritten the next time it is regenerated.
// If you want to change its behavior, extend or call the classes and functions
// declared in this generated file instead.
// The authors accept no responsibility for anything that results from using this
// generated file, and managing it in a version control system such as git or svn
// is not recommended.
//
// Generated at: <normalized>
// Generated on: <normalized>
// Generator OS: <normalized>
// PHP version: <normalized>

#[allow(dead_code, non_camel_case_types, non_snake_case, unused_imports)]
pub mod bridge {

use std::ffi::{c_char, c_void};
use std::os::raw::{c_double, c_float, c_int, c_long, c_longlong, c_schar, c_short, c_uchar, c_uint, c_ulong, c_ulonglong, c_ushort};

mod native {
    use super::*;
    unsafe extern "C" {
        pub fn example_version() -> *mut c_char;
        pub fn example_add(left: c_int, right: c_int) -> c_int;
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pnlx_bridge_example_version() -> *mut c_char {
    unsafe { native::example_version() }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pnlx_bridge_example_add(left: c_int, right: c_int) -> c_int {
    unsafe { native::example_add(left, right) }
}



}
