<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * Base wrapper around an `\FFI\CData` pointer produced or consumed by {@see Example}.
 *
 * Concrete per-type wrappers under {@see Example\Types} extend this class, and an
 * opaque (`void *`) value falls back to it directly. Methods that take a pointer
 * accept any {@see \Pnlx\Types\PointerInterface}; the inner `\FFI\CData` is
 * unwrapped via {@see toValue()} before the native call. Pass {@see cdata()}
 * when you need the underlying value.
 */
class ExampleContext implements \Pnlx\Types\PointerInterface
{
    public function __construct(
        protected readonly \FFI\CData $cdata,
    ) {
    }

    /** The wrapped FFI value. */
    public function cdata(): \FFI\CData
    {
        return $this->cdata;
    }

    public function toValue(): \FFI\CData
    {
        return $this->cdata;
    }
}
