<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * Generated entrypoint for the example/example native library.
 *
 * A C library is a bag of functions, so call this entity statically and never
 * instantiate it: `Example::some_c_function(...)`. The methods named after C
 * functions live in the {@see ExampleLibraryComponent} trait this class mixes in;
 * all the wiring lives in {@see \Pnlx\Extension\AbstractExtension}, so nothing here
 * can be shadowed by a C function.
 *
 * Install-time metadata (name/version/description and the resolved native library
 * path/hash/co-load libraries) rides on the `#[\Pnlx\Attribute\NativeLibrary]`
 * attribute — read it via `\Pnlx\FFI\NativeLibraryRegistry::info(Example::class)`.
 * It is an attribute, not constants, so a composed class can mix in several
 * Component traits without colliding metadata.
 */
#[\Pnlx\Attribute\NativeLibrary(
    name: 'example/example',
    version: '1.2.3',
    description: 'Test fixture native library.',
    // The resolved native library path and content hash, stamped in at install time.
    path: '<normalized>',
    hash: '<normalized>',
    cdef: 'example.ffi.php',
    aliases: 'function.aliases.php',
    // Extra shared libraries co-loaded alongside this one, stamped in at install time.
    libraries: [],
)]
#[\Pnlx\Attribute\AutoGeneratedByPnlx]
class Example extends \Pnlx\Extension\AbstractExtension
{
    use ExampleLibraryComponent;
}
