<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

use Pnlx\Exception\PHPNativeLibraryException;

/**
 * Base exception for failures raised by the generated {@see Example} extension.
 *
 * Extends {@see PHPNativeLibraryException} (which extends \RuntimeException), so a
 * single `catch (ExampleException $e)` narrows to this library while
 * `catch (PHPNativeLibraryException $e)` still catches any pnl runtime failure.
 */
class ExampleException extends PHPNativeLibraryException
{
}
