<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

use Pnlx\ContextInterface;
use Pnlx\Exception\ExtensionLoadException;
use Pnlx\RuntimeInterface;

class ExampleContext implements ContextInterface
{
    public function __construct(
        private readonly RuntimeInterface $runtime,
    ) {
    }

    public function name(): string
    {
        return $this->manifest()['name'];
    }

    public function version(): string
    {
        return $this->manifest()['version'];
    }

    public function hash(): string
    {
        return $this->bridge()['sha256'];
    }

    public function description(): string
    {
        return $this->manifest()['description'];
    }

    public function path(): string
    {
        return $this->absolutePath($this->bridge()['library']);
    }

    /**
     * @return array<string, mixed>
     */
    protected function manifest(): array
    {
        return $this->runtime->manifest(Example::class);
    }

    /**
     * @return array{source: string, library: string, sha256: string}
     */
    protected function bridge(): array
    {
        $bridge = $this->runtime->pathmap()['bridges']['example'] ?? null;
        if (!is_array($bridge)) {
            throw new ExtensionLoadException('Bridge example is not installed.');
        }

        foreach (['source', 'library', 'sha256'] as $key) {
            if (!isset($bridge[$key]) || !is_string($bridge[$key]) || $bridge[$key] === '') {
                throw new ExtensionLoadException(sprintf('Bridge example is missing %s.', $key));
            }
        }

        return $bridge;
    }

    protected function absolutePath(string $path): string
    {
        if (str_starts_with($path, '/')) {
            return $path;
        }

        return $this->runtime->projectRoot() . '/' . $path;
    }
}
