<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

return [
    'ExampleAdd' => 'example_add',
    'ExampleApply' => 'example_apply',
    'ExampleNextMode' => 'example_next_mode',
    'ExampleOpaqueRead' => 'example_opaque_read',
    'ExampleOpaqueWrite' => 'example_opaque_write',
    'ExamplePointInit' => 'example_point_init',
    'ExamplePointSum' => 'example_point_sum',
    'ExampleValueInit' => 'example_value_init',
    'ExampleValueInteger' => 'example_value_integer',
    'ExampleVersion' => 'example_version',
    'exampleAdd' => 'example_add',
    'exampleApply' => 'example_apply',
    'exampleNextMode' => 'example_next_mode',
    'exampleOpaqueRead' => 'example_opaque_read',
    'exampleOpaqueWrite' => 'example_opaque_write',
    'examplePointInit' => 'example_point_init',
    'examplePointSum' => 'example_point_sum',
    'exampleValueInit' => 'example_value_init',
    'exampleValueInteger' => 'example_value_integer',
    'exampleVersion' => 'example_version',
    'example_add' => 'example_add',
    'example_apply' => 'example_apply',
    'example_next_mode' => 'example_next_mode',
    'example_opaque_read' => 'example_opaque_read',
    'example_opaque_write' => 'example_opaque_write',
    'example_point_init' => 'example_point_init',
    'example_point_sum' => 'example_point_sum',
    'example_value_init' => 'example_value_init',
    'example_value_integer' => 'example_value_integer',
    'example_version' => 'example_version',
    'exampleadd' => 'example_add',
    'exampleapply' => 'example_apply',
    'examplenextmode' => 'example_next_mode',
    'exampleopaqueread' => 'example_opaque_read',
    'exampleopaquewrite' => 'example_opaque_write',
    'examplepointinit' => 'example_point_init',
    'examplepointsum' => 'example_point_sum',
    'examplevalueinit' => 'example_value_init',
    'examplevalueinteger' => 'example_value_integer',
    'exampleversion' => 'example_version',
];
