<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * Global helpers live under the Pnlx\Func\Example namespace (one segment per
 * package, so same-named functions across libraries never collide). Call them
 * fully qualified, e.g. Pnlx\Func\Example\example_add(2, 3), or import them
 * with `use function Pnlx\Func\Example\example_add;`.
 */

namespace Pnlx\Func\Example;

if (!function_exists('Pnlx\\Func\\Example\\example_version')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    function example_version(): string|\Pnlx\Types\String_|null
    {
        return \Pnlx\Example\Example::example_version(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_next_mode')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_next_mode')]
    function example_next_mode(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $mode): \Pnlx\Example\Enums\example_mode|null
    {
        return \Pnlx\Example\Example::example_next_mode(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_add')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    function example_add(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $right): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_add(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_apply')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_apply')]
    function example_apply(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $value, callable|\FFI\CData|null $callback): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_apply(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_opaque_read')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_opaque_read')]
    function example_opaque_read(string|\Pnlx\Example\Types\example_opaque|\Pnlx\Types\PointerInterface|null|\FFI\CData $value): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_opaque_read(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_point_sum')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_sum')]
    function example_point_sum(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_point_sum(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_value_integer')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_value_integer')]
    function example_value_integer(string|\Pnlx\Example\Types\example_value|\Pnlx\Types\PointerInterface|null|\FFI\CData $value): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_value_integer(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_opaque_write')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_opaque_write')]
    function example_opaque_write(string|\Pnlx\Example\Types\example_opaque|\Pnlx\Types\PointerInterface|null|\FFI\CData $value, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $word): void
    {
        \Pnlx\Example\Example::example_opaque_write(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_point_init')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_init')]
    function example_point_init(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $x, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $y): void
    {
        \Pnlx\Example\Example::example_point_init(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_value_init')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_value_init')]
    function example_value_init(string|\Pnlx\Example\Types\example_value|\Pnlx\Types\PointerInterface|null|\FFI\CData $value, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $integer): void
    {
        \Pnlx\Example\Example::example_value_init(...func_get_args());
    }
}

