<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * Global helpers live under the Pnlx\Func\Example namespace (one segment per
 * package, so same-named functions across libraries never collide). Call them
 * fully qualified, e.g. Pnlx\Func\Example\example_add(2, 3), or import them
 * with `use function Pnlx\Func\Example\example_add;`.
 */

namespace Pnlx\Func\Example;

if (!function_exists('Pnlx\\Func\\Example\\example_version')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    function example_version(): string|\Pnlx\Types\String_|null
    {
        return \Pnlx\Example\Example::example_version(...func_get_args());
    }
}

if (!function_exists('Pnlx\\Func\\Example\\example_add')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    function example_add(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $right): int|\Pnlx\Types\Int_
    {
        return \Pnlx\Example\Example::example_add(...func_get_args());
    }
}

