<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

return [
    'ExampleAdd' => 'pnlx_bridge_example_add',
    'ExampleVersion' => 'pnlx_bridge_example_version',
    'exampleAdd' => 'pnlx_bridge_example_add',
    'exampleVersion' => 'pnlx_bridge_example_version',
    'example_add' => 'pnlx_bridge_example_add',
    'example_version' => 'pnlx_bridge_example_version',
    'exampleadd' => 'pnlx_bridge_example_add',
    'exampleversion' => 'pnlx_bridge_example_version',
];
