<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

require_once __DIR__ . '/ExampleManifest.php';
require_once __DIR__ . '/ExampleContext.php';
require_once __DIR__ . '/ExampleException.php';

// Object-like #define constants from the C header, as namespaced PHP consts.
require_once __DIR__ . '/const.php';

// Function-like C macros as PHP functions under \Pnlx\Func\<Class> (always loaded).
require_once __DIR__ . '/macro.functions.php';

// The per-C-type pointer wrappers, one class per file under types/.
foreach (glob(__DIR__ . '/types/*.php') ?: [] as $typeFile) {
    require_once $typeFile;
}

// Two feature flags select one of the four generated entity variants at runtime:
// `allow_cdata` (the cdata/ subdir, params also accept raw \FFI\CData) and
// `use_php_scalars_in_return` (the scalar/ subdir, methods return native scalars).
$entityVariant = '';
if (\Pnlx\Runtime::allowCData()) {
    $entityVariant .= 'cdata/';
}
if (\Pnlx\Runtime::useScalarsInReturn()) {
    $entityVariant .= 'scalar/';
}
// Requiring the entity boots it (its bottom-of-file `initialize()` runs once),
// so the class is ready for static calls — no runtime instance is kept here.
require_once __DIR__ . '/' . $entityVariant . 'Example.php';
unset($entityVariant);

if (is_file(__DIR__ . '/preload.php')) {
    require __DIR__ . '/preload.php';
}

// Global helper functions (when enabled) just delegate to the static entity.
if (\Pnlx\Runtime::enableFunctions()) {
    require_once __DIR__ . '/functions.php';
}

if (is_file(__DIR__ . '/postload.php')) {
    require __DIR__ . '/postload.php';
}
