<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

require_once __DIR__ . '/ExampleContext.php';
require_once __DIR__ . '/Example.php';

$runtimeVarName = 'runtime_6cb1b74a9104bd0eeefa7e6d7fd08b2fefed1647746599904aa7415da88519fe';
$runtime = new \Pnlx\Runtime();

if (is_file(__DIR__ . '/preload.php')) {
    require __DIR__ . '/preload.php';
}

if (\Pnlx\Runtime::enableFunctions()) {
    $GLOBALS[$runtimeVarName] = $runtime->load(\Pnlx\Example\Example::class);

    require_once __DIR__ . '/functions.php';
}

if (is_file(__DIR__ . '/postload.php')) {
    require __DIR__ . '/postload.php';
}

unset($runtimeVarName);
unset($runtime);
