<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * Function-like C macros surfaced as PHP functions under the Pnlx\Func\Example
 * namespace. They delegate to the static entity (and, for cross-package macros,
 * to a dependency's entity). Always loaded, independent of features.global_functions.
 */

namespace Pnlx\Func\Example;

if (!function_exists('Pnlx\Func\Example\EXAMPLE_MISSING')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('EXAMPLE_MISSING')]
    function EXAMPLE_MISSING($X)
    {
        throw new \Pnlx\Exception\PHPNativeLibraryException('EXAMPLE_MISSING calls the undefined C function example_absent.');
    }
}

if (!function_exists('Pnlx\Func\Example\EXAMPLE_TWICE')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('EXAMPLE_TWICE')]
    function EXAMPLE_TWICE($N)
    {
        return \Pnlx\Example\Example::example_add($N, $N);
    }
}


