use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};

use crate::io::{read_json, write_json};
use crate::manifest::{PnlLock, PnlxManifest, PnlxPathmap};
use crate::platform::{GeneratedMetadata, current_platform};
use crate::validate::{ensure_platform_matches, validate_pnlx_pathmap_values};

pub(super) fn pnlx_workspace_dir(root: &Path) -> PathBuf {
    crate::workspace::workspace_dir(root)
}

pub(super) fn pnl_lock_path(root: &Path) -> PathBuf {
    // The lockfile lives next to pnl.json (not inside the configurable output
    // dir) so it has a fixed, committable location independent of `output_dir`.
    root.join("pnlx-lock.json")
}

pub(super) fn pnlx_pathmap_path(root: &Path) -> PathBuf {
    pnlx_workspace_dir(root).join("pnlx-pathmap.json")
}

pub(super) fn install_extension_files(
    root: &Path,
    source: &Path,
    package: &str,
    version: &str,
) -> Result<PathBuf> {
    let destination = installed_extension_dir(root, package, version);
    let parent = destination
        .parent()
        .with_context(|| format!("{} has no parent directory", destination.display()))?;
    fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;

    let temp = parent.join(format!(".{version}.{}.tmp", std::process::id()));
    let backup = parent.join(format!(".{version}.{}.bak", std::process::id()));
    if temp.exists() {
        fs::remove_dir_all(&temp)
            .with_context(|| format!("failed to remove {}", temp.display()))?;
    }
    if backup.exists() {
        fs::remove_dir_all(&backup)
            .with_context(|| format!("failed to remove {}", backup.display()))?;
    }

    copy_package_directory(source, source, &temp)?;

    let had_previous = destination.exists();
    if had_previous {
        fs::rename(&destination, &backup).with_context(|| {
            format!(
                "failed to move {} to {}",
                destination.display(),
                backup.display()
            )
        })?;
    }
    if let Err(error) = fs::rename(&temp, &destination) {
        if had_previous {
            let _ = fs::rename(&backup, &destination);
        }
        bail!(
            "failed to install {} to {}: {error}",
            source.display(),
            destination.display()
        );
    }
    if backup.exists() {
        fs::remove_dir_all(&backup)
            .with_context(|| format!("failed to remove {}", backup.display()))?;
    }
    Ok(destination)
}

/// The directory holding every installed version of a package:
/// `<workspace>/packages/<vendor>/<package>`.
pub(super) fn installed_package_dir(root: &Path, package: &str) -> PathBuf {
    let mut path = pnlx_workspace_dir(root).join("packages");
    for segment in package.split('/') {
        path.push(segment);
    }
    path
}

/// A specific installed version of a package:
/// `<workspace>/packages/<vendor>/<package>/<version>`.
pub(super) fn installed_extension_dir(root: &Path, package: &str, version: &str) -> PathBuf {
    installed_package_dir(root, package).join(version)
}

pub(super) fn write_pnlx_autoload(root: &Path) -> Result<()> {
    let autoload_path = pnlx_workspace_dir(root).join("autoload.php");
    let packages = collect_installed_packages(root)?;
    let metadata = GeneratedMetadata::current();
    let version = env!("CARGO_PKG_VERSION");
    let mut content = format!(
        r#"<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: {generated_at}
 * Generated on: {host}
 * Generator OS: {os}
 * PHP version: {php_version}
 */

/** The version of the pnl/pnlx toolchain that generated this file. */
const PNL_VERSION = '{version}';
const PNLX_VERSION = '{version}';

"#,
        generated_at = metadata.generated_at,
        host = metadata.host,
        os = metadata.os,
        php_version = metadata.php_version,
    );

    for package in &packages {
        content.push_str("require_once __DIR__ . '/");
        content.push_str(&php_single_quoted_path(&package.entrypoint));
        content.push_str("';\n");
    }

    content.push('\n');
    content.push_str(&installed_helpers_php(&packages));

    if let Some(parent) = autoload_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(&autoload_path, content)
        .with_context(|| format!("failed to write {}", autoload_path.display()))?;
    Ok(())
}

/// Render the global `pnl_installed_native_libraries()` / `pnl_is_installed()`
/// helpers, with the installed-package map baked in for the install check.
fn installed_helpers_php(packages: &[InstalledPackage]) -> String {
    let mut map = String::new();
    for package in packages {
        let classes = package
            .classes
            .iter()
            .map(|class| format!("'{}'", php_single_quoted_path(class)))
            .collect::<Vec<_>>()
            .join(", ");
        map.push_str(&format!(
            "        '{name}' => ['version' => '{version}', 'classes' => [{classes}]],\n",
            name = php_single_quoted_path(&package.name),
            version = php_single_quoted_path(&package.version),
        ));
    }

    format!(
        r#"if (!function_exists('pnl_installed_native_libraries')) {{
    /**
     * List every native library resolved into this workspace's pathmap.
     *
     * @return list<array{{version: string, name: string, hash: string, paths: array{{header: ?string, library: string}}, installed_at: ?string}}>
     */
    function pnl_installed_native_libraries(): array
    {{
        return \Pnlx\Installed\InstalledLibraries::nativeLibraries(__DIR__ . '/pnlx-pathmap.json');
    }}
}}

if (!function_exists('pnl_is_installed')) {{
    /**
     * Whether an extension is installed, optionally constrained to a version.
     *
     * `$extension` accepts a generated class name (e.g. `Libsdl::class`) or a
     * `vendor/package` name (e.g. `libsdl/libsdl`). `$version`, when given, is a
     * constraint such as `>3.0.0 & <4.0.0`.
     */
    function pnl_is_installed(string $extension, ?string $version = null): bool
    {{
        return \Pnlx\Installed\InstalledLibraries::isInstalled([
{map}        ], $extension, $version);
    }}
}}
"#,
    )
}

pub(super) fn read_lock_for_current_platform(root: &Path) -> Result<PnlLock> {
    let platform = current_platform();
    let lock_path = pnl_lock_path(root);
    if !lock_path.exists() {
        return Ok(PnlLock::empty(platform));
    }

    let lock = read_json::<PnlLock>(&lock_path)?;
    if lock.platform == platform {
        Ok(lock)
    } else {
        Ok(PnlLock::empty(platform))
    }
}

pub(super) fn read_pathmap_for_current_platform(root: &Path) -> Result<PnlxPathmap> {
    let path = pnlx_pathmap_path(root);
    if !path.exists() {
        return Ok(PnlxPathmap::empty_current());
    }

    let pathmap = read_json::<PnlxPathmap>(&path)?;
    ensure_platform_matches(&pathmap.platform)?;
    validate_pnlx_pathmap_values(&pathmap)?;
    Ok(pathmap)
}

pub(super) fn write_pathmap(root: &Path, pathmap: &PnlxPathmap) -> Result<()> {
    write_json(&pnlx_pathmap_path(root), pathmap)
}

pub(super) fn sha256_file(path: &Path) -> Result<String> {
    let mut file =
        fs::File::open(path).with_context(|| format!("failed to read {}", path.display()))?;
    let mut digest = Sha256::new();
    let mut buffer = [0u8; 64 * 1024];
    loop {
        let read = file
            .read(&mut buffer)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if read == 0 {
            break;
        }
        digest.update(&buffer[..read]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

pub(super) fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("{digest:x}")
}

/// Content digest of a package directory used as an integrity signature.
///
/// Files are sorted by relative path (A–z); each file's content is hashed with
/// sha256, then all of those per-file hashes are hashed together into a single
/// sha256. Generated output, `.git`, and the workspace directory are excluded so
/// the digest reflects only the package's own source.
pub(super) fn tree_sha256(root: &Path) -> Result<String> {
    let mut files = Vec::new();
    collect_package_files(root, root, &mut files)?;
    files.sort();

    let mut hasher = Sha256::new();
    for relative in &files {
        let file_hash = sha256_file(&root.join(relative))?;
        hasher.update(relative.as_bytes());
        hasher.update(b"\0");
        hasher.update(file_hash.as_bytes());
        hasher.update(b"\n");
    }
    Ok(format!("{:x}", hasher.finalize()))
}

fn collect_package_files(root: &Path, dir: &Path, files: &mut Vec<String>) -> Result<()> {
    for entry in fs::read_dir(dir).with_context(|| format!("failed to read {}", dir.display()))? {
        let path = entry
            .with_context(|| format!("failed to read {}", dir.display()))?
            .path();
        if should_skip_package_copy(root, &path) {
            continue;
        }
        if path.is_dir() {
            collect_package_files(root, &path, files)?;
        } else {
            files.push(relative_slash_path(root, &path));
        }
    }
    Ok(())
}

fn relative_slash_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

pub(super) fn relative_to_root(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

pub(super) fn json_string(path: &Path) -> String {
    serde_json::to_string(&path.display().to_string()).expect("path string is serializable")
}

pub(super) fn absolutize(root: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        root.join(path)
    }
}

pub(super) fn file_url_for_path(path: &Path) -> String {
    let path = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    url::Url::from_file_path(&path)
        .map(String::from)
        .unwrap_or_else(|()| format!("file://{}", path.display()))
}

fn copy_package_directory(source_root: &Path, source: &Path, destination: &Path) -> Result<()> {
    fs::create_dir_all(destination)
        .with_context(|| format!("failed to create {}", destination.display()))?;

    for entry in
        fs::read_dir(source).with_context(|| format!("failed to read {}", source.display()))?
    {
        let entry = entry.with_context(|| format!("failed to read {}", source.display()))?;
        let source_path = entry.path();
        if should_skip_package_copy(source_root, &source_path) {
            continue;
        }

        let destination_path = destination.join(entry.file_name());
        if source_path.is_dir() {
            copy_package_directory(source_root, &source_path, &destination_path)?;
        } else {
            if let Some(parent) = destination_path.parent() {
                fs::create_dir_all(parent)
                    .with_context(|| format!("failed to create {}", parent.display()))?;
            }
            fs::copy(&source_path, &destination_path).with_context(|| {
                format!(
                    "failed to copy {} to {}",
                    source_path.display(),
                    destination_path.display()
                )
            })?;
        }
    }

    Ok(())
}

fn should_skip_package_copy(source_root: &Path, source_path: &Path) -> bool {
    let relative = source_path.strip_prefix(source_root).unwrap_or(source_path);
    relative == Path::new("src/generated")
        || relative.starts_with(".git")
        || relative.starts_with(crate::workspace::output_dir_name(source_root).as_str())
}

/// One installed package version, as needed to build `@pnlx/autoload.php`.
struct InstalledPackage {
    /// Generated entrypoint, relative to the `@pnlx` workspace directory.
    entrypoint: String,
    /// Extension name (`vendor/package`).
    name: String,
    /// Installed version.
    version: String,
    /// Fully qualified generated class names this package exposes.
    classes: Vec<String>,
}

fn collect_installed_packages(root: &Path) -> Result<Vec<InstalledPackage>> {
    let packages_root = pnlx_workspace_dir(root).join("packages");
    if !packages_root.is_dir() {
        return Ok(Vec::new());
    }

    let mut packages = Vec::new();
    for vendor in fs::read_dir(&packages_root)
        .with_context(|| format!("failed to read {}", packages_root.display()))?
    {
        let vendor =
            vendor.with_context(|| format!("failed to read {}", packages_root.display()))?;
        if !vendor.path().is_dir() {
            continue;
        }

        for package in fs::read_dir(vendor.path())
            .with_context(|| format!("failed to read {}", vendor.path().display()))?
        {
            let package =
                package.with_context(|| format!("failed to read {}", vendor.path().display()))?;
            if !package.path().is_dir() {
                continue;
            }

            // Each package holds one directory per installed version.
            for version in fs::read_dir(package.path())
                .with_context(|| format!("failed to read {}", package.path().display()))?
            {
                let version = version
                    .with_context(|| format!("failed to read {}", package.path().display()))?;
                let manifest_path = version.path().join("pnlx.json");
                if !manifest_path.is_file() {
                    continue;
                }

                let manifest = read_json::<PnlxManifest>(&manifest_path)?;
                let entrypoint = version.path().join(&manifest.entrypoint);
                if entrypoint.is_file() {
                    packages.push(InstalledPackage {
                        entrypoint: relative_to_pnlx(root, &entrypoint),
                        name: manifest.name.clone(),
                        version: manifest.version.clone(),
                        classes: entity_class_fqn(&manifest).into_iter().collect(),
                    });
                }
            }
        }
    }

    packages.sort_by(|a, b| a.entrypoint.cmp(&b.entrypoint));
    Ok(packages)
}

/// The fully qualified generated entity class name (namespace + `class_prefix` +
/// base class), or `None` when the manifest class carries no namespace.
fn entity_class_fqn(manifest: &PnlxManifest) -> Option<String> {
    let normalized = manifest.class.replace("\\\\", "\\");
    let (namespace, class_name) = normalized.rsplit_once('\\')?;
    Some(format!(
        "{namespace}\\{}{class_name}",
        manifest.class_prefix
    ))
}

fn relative_to_pnlx(root: &Path, path: &Path) -> String {
    path.strip_prefix(pnlx_workspace_dir(root))
        .unwrap_or(path)
        .display()
        .to_string()
}

fn php_single_quoted_path(path: &str) -> String {
    path.replace('\\', "\\\\").replace('\'', "\\'")
}
