// !!! DO NOT EDIT THIS FILE !!!
//
// This file was generated automatically by a machine, so any changes you make to
// it may be overwritten the next time it is regenerated.
// If you want to change its behavior, extend or call the classes and functions
// declared in this generated file instead.
// The authors accept no responsibility for anything that results from using this
// generated file, and managing it in a version control system such as git or svn
// is not recommended.
//
// Generated at: {{GENERATED_AT}}
// Generated on: {{GENERATED_HOST}}
// Generator OS: {{GENERATED_OS}}
// PHP version: {{GENERATED_PHP_VERSION}}

#[allow(dead_code, non_camel_case_types, non_snake_case, unused_imports)]
pub mod bridge {

use std::ffi::{c_char, c_void};
use std::os::raw::{c_double, c_float, c_int, c_long, c_longlong, c_schar, c_short, c_uchar, c_uint, c_ulong, c_ulonglong, c_ushort};

{{FUNCTIONS}}

}
