<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: {{GENERATED_AT}}
 * Generated on: {{GENERATED_HOST}}
 * Generator OS: {{GENERATED_OS}}
 * PHP version: {{GENERATED_PHP_VERSION}}
 */

namespace {{NAMESPACE}};

use Pnlx\Exception\ExtensionLoadException;
use Pnlx\FFI\NativeLibrary;
use Pnlx\RuntimeInterface;

class {{CLASS}}
{
    protected NativeLibrary $native;

    protected RuntimeInterface $runtime;

    protected {{CLASS}}Context $context;

    public function __construct(RuntimeInterface $runtime)
    {
        $this->runtime = $runtime;
        $context = $runtime->context(self::class);
        if (!$context instanceof {{CLASS}}Context) {
            throw new ExtensionLoadException(sprintf(
                'Extension context for %s must be an instance of %s.',
                self::class,
                {{CLASS}}Context::class
            ));
        }
        $this->context = $context;

        if (!is_file($this->context->path())) {
            throw new ExtensionLoadException('an extension cannot be loaded');
        }

        $this->native = $runtime->native(self::class, '{{FFI_FILE}}');
    }

    public function __call(string $name, array $arguments): mixed
    {
        return $this->native->call($name, $arguments);
    }

{{METHODS}}
}
