<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * Generated entrypoint for the example/example native library.
 *
 * A C library is a bag of functions, so call this entity statically and never
 * instantiate it: `Example::some_c_function(...)`. All the wiring lives in the
 * shared {@see \Pnlx\Extension\AbstractExtension} base behind the magic
 * `__callStatic`, so this class holds ONLY the methods named after C functions
 * (plus the metadata constants) and nothing here can be shadowed by one.
 *
 * Metadata is build-time information baked in as constants: `Example::NAME`,
 * `VERSION`, `HASH`, `DESCRIPTION`, `PATH`. `HASH`/`PATH` describe the compiled
 * bridge and are stamped in once it has been built.
 */
#[\Pnlx\Attribute\NativeLibraryName('example/example')]
#[\Pnlx\Attribute\NativeLibraryVersion('1.2.3')]
#[\Pnlx\Attribute\AutoGeneratedByPnlx]
class Example extends \Pnlx\Extension\AbstractExtension
{
    protected const string FFI_FILE = 'example.ffi.php';

    public const string NAME = 'example/example';

    public const string VERSION = '1.2.3';

    public const string DESCRIPTION = 'Test fixture native library.';

    // The compiled bridge's path and content hash, stamped in after it is built.
    public const string PATH = '<normalized>';

    public const string HASH = '<normalized>';

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function exampleVersion(): string
    {
        return \Pnlx\Util::cString(static::__callStatic('exampleVersion', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function example_version(): string
    {
        return \Pnlx\Util::cString(static::__callStatic('example_version', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function exampleAdd(int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $right): int
    {
        return (int) static::__callStatic('exampleAdd', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function example_add(int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $right): int
    {
        return (int) static::__callStatic('example_add', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
    }


}

// One-time boot: the first static call boots and returns without dispatching, so
// running it here (at load) means every later `Example::c_function(...)` call
// dispatches straight to the native library. `initialize` is not a real method —
// it is caught by the base `__callStatic`, so it can never clash with a C
// function of the same name.
Example::initialize();
