<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * Generated entrypoint for the example/example native library.
 *
 * All the wiring (constructor, `__get`, `__call`, fields) lives in the shared
 * {@see \Pnlx\Extension\AbstractExtension} base, so this class holds ONLY the
 * methods named after C functions and nothing here can be shadowed by one.
 * Metadata is reachable as `$ext->manifest->name()` and, via the base's
 * `__get()`, as read-only fields:
 *
 * @property-read string $name        The native library's package name.
 * @property-read string $version     The native library's package version.
 * @property-read string $hash        Content hash of the compiled native bridge.
 * @property-read string $description The package description from the manifest.
 * @property-read string $path        Absolute path of the compiled native bridge.
 */
#[\Pnlx\Attribute\NativeLibraryName('example/example')]
#[\Pnlx\Attribute\NativeLibraryVersion('1.2.3')]
#[\Pnlx\Attribute\AutoGeneratedByPnlx]
class Example extends \Pnlx\Extension\AbstractExtension
{
    protected const string FFI_FILE = 'example.ffi.php';

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public function exampleVersion(): string
    {
        return \Pnlx\Util::cString($this->__call('exampleVersion', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public function example_version(): string
    {
        return \Pnlx\Util::cString($this->__call('example_version', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public function exampleAdd(int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $right): int
    {
        return (int) $this->__call('exampleAdd', [\Pnlx\FFI\ArgumentMarshaller::scalarArg($left, $this->scalarParamsAllowed), \Pnlx\FFI\ArgumentMarshaller::scalarArg($right, $this->scalarParamsAllowed)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public function example_add(int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Helpers\AnySizeInteger|\FFI\CData $right): int
    {
        return (int) $this->__call('example_add', [\Pnlx\FFI\ArgumentMarshaller::scalarArg($left, $this->scalarParamsAllowed), \Pnlx\FFI\ArgumentMarshaller::scalarArg($right, $this->scalarParamsAllowed)]);
    }


}
