<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: {{GENERATED_AT}}
 * Generated on: {{GENERATED_HOST}}
 * Generator OS: {{GENERATED_OS}}
 * PHP version: {{GENERATED_PHP_VERSION}}
 */

/** The version of the pnl/pnlx toolchain that generated this file. */
const PNL_VERSION = '{{VERSION}}';
const PNLX_VERSION = '{{VERSION}}';

/*
 * The absolute path of the pnl.json this workspace was generated from, captured
 * at install/init time. Pnlx\Runtime reads it when constructed without an
 * explicit path, so the workspace loads regardless of the current directory.
 */
const PNLX_PROJECT_MANIFEST = '{{PROJECT_MANIFEST}}';
const PNL_PROJECT_MANIFEST = PNLX_PROJECT_MANIFEST;

/*
 * The built-in configuration baked into the pnl/pnlx binary (config.toml),
 * exposed verbatim so PHP code can read the same defaults the toolchain uses.
 */
const PNL_CONFIG_SCHEMA_VERSION = '{{CONFIG_SCHEMA_VERSION}}';
const PNLX_CONFIG_SCHEMA_VERSION = '{{CONFIG_SCHEMA_VERSION}}';
const PNL_CONFIG_SELF_REPOSITORY = '{{CONFIG_SELF_REPOSITORY}}';
const PNLX_CONFIG_SELF_REPOSITORY = '{{CONFIG_SELF_REPOSITORY}}';
const PNL_CONFIG_PACKAGES_REPOSITORY = '{{CONFIG_PACKAGES_REPOSITORY}}';
const PNLX_CONFIG_PACKAGES_REPOSITORY = '{{CONFIG_PACKAGES_REPOSITORY}}';
const PNL_CONFIG_OUTPUT_DIR = '{{CONFIG_OUTPUT_DIR}}';
const PNLX_CONFIG_OUTPUT_DIR = '{{CONFIG_OUTPUT_DIR}}';
const PNL_CONFIG_UPDATE_CHECK_TTL_SECONDS = {{CONFIG_TTL_SECONDS}};
const PNLX_CONFIG_UPDATE_CHECK_TTL_SECONDS = {{CONFIG_TTL_SECONDS}};
const PNL_CONFIG_UPDATE_CHECK_OPT_OUT_ENV = '{{CONFIG_OPT_OUT_ENV}}';
const PNLX_CONFIG_UPDATE_CHECK_OPT_OUT_ENV = '{{CONFIG_OPT_OUT_ENV}}';
const PNL_CONFIG_UPDATE_CHECK_CACHE_KEY = '{{CONFIG_CACHE_KEY}}';
const PNLX_CONFIG_UPDATE_CHECK_CACHE_KEY = '{{CONFIG_CACHE_KEY}}';
const PNL_CONFIG_BINARIES = [{{#each CONFIG_BINARIES}}'{{this}}'{{#unless @last}}, {{/unless}}{{/each}}];
const PNLX_CONFIG_BINARIES = [{{#each CONFIG_BINARIES}}'{{this}}'{{#unless @last}}, {{/unless}}{{/each}}];

/** The build target (OS/arch) of the pnl/pnlx binary that generated this file. */
const PNLX_BUILD_OS = '{{BUILD_OS}}';
const PNLX_BUILD_ARCH = '{{BUILD_ARCH}}';

require_once __DIR__ . '/runtime/autoload.php';

require_once __DIR__ . '/ide-helper.php';

{{#each PACKAGES}}require_once __DIR__ . '/{{this}}';
{{/each}}
// Composed classes (see `pnl compose`) are required after the packages they mix
// in, so their Component traits are already defined.
{{#each COMPOSITES}}require_once __DIR__ . '/{{this}}';
{{/each}}
if (!function_exists('pnl_installed_native_libraries')) {
    /**
     * List every native library resolved into this workspace's pathmap.
     *
     * @return list<array{version: string, name: string, hash: string, paths: array{header: ?string, library: string}, installed_at: ?string}>
     */
    function pnl_installed_native_libraries(): array
    {
        return \Pnlx\Installed\InstalledLibraries::nativeLibraries(__DIR__ . '/pnlx-pathmap.json');
    }
}

if (!function_exists('pnl_is_installed')) {
    /**
     * Whether an extension is installed, optionally constrained to a version.
     *
     * Resolved through the pathmap (which records the lockfile's location), so no
     * fixed layout is assumed. `$extension` accepts a generated class name
     * (e.g. `Example::class`) or a `vendor/package` name; `$version`, when given,
     * is a constraint such as `>3.0.0 & <4.0.0`.
     */
    function pnl_is_installed(string $extension, ?string $version = null): bool
    {
        return \Pnlx\Installed\InstalledLibraries::isInstalledFromPathmap(
            __DIR__ . '/pnlx-pathmap.json',
            $extension,
            $version
        );
    }
}
