<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: {{GENERATED_AT}}
 * Generated on: {{GENERATED_HOST}}
 * Generator OS: {{GENERATED_OS}}
 * PHP version: {{GENERATED_PHP_VERSION}}
 *
 * IDE helper: stub declarations for the PHP FFI types referenced by generated
 * extension wrappers. They are guarded by class_exists(), so when the ffi
 * extension is loaded this file does nothing at runtime; editors still index the
 * stubs so `\FFI` and `\FFI\CData` resolve for autocompletion and static analysis.
 */

namespace FFI {
    if (!class_exists(\FFI\CData::class)) {
        /** @see https://www.php.net/manual/en/class.ffi-cdata.php */
        class CData
        {
        }
    }

    if (!class_exists(\FFI\CType::class)) {
        /** @see https://www.php.net/manual/en/class.ffi-ctype.php */
        class CType
        {
        }
    }
}

namespace {
    if (!class_exists(\FFI::class)) {
        /** @see https://www.php.net/manual/en/class.ffi.php */
        class FFI
        {
            public static function cdef(string $code = '', ?string $lib = null): \FFI
            {
            }

            public static function load(string $filename): ?\FFI
            {
            }

            public static function new(\FFI\CType|string $type, bool $owned = true, bool $persistent = false): \FFI\CData
            {
            }

            public static function cast(\FFI\CType|string $type, \FFI\CData|int|float|bool|null $ptr): \FFI\CData
            {
            }

            public static function type(string $type): \FFI\CType
            {
            }

            public static function addr(\FFI\CData $ptr): \FFI\CData
            {
            }

            public static function sizeof(\FFI\CData|\FFI\CType $ptr): int
            {
            }

            public static function string(\FFI\CData $ptr, ?int $size = null): string
            {
            }

            public static function isNull(\FFI\CData $ptr): bool
            {
            }

            public static function memcpy(\FFI\CData $to, mixed $from, int $size): void
            {
            }
        }
    }
}
