{{~#*inline "param"~}}
{{#if callback}}callable{{#if cdata}}|\FFI\CData{{/if}}|null ${{name}}{{else}}{{#if native_pointer}}#[\Pnlx\Attribute\NativePointer('{{np_element}}'{{#if np_string}}, string: true{{/if}}{{#if np_wrap}}, wrap: '{{np_wrap}}'{{/if}}{{#if np_buffer}}, buffer: true{{/if}})] {{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable{{/if}}{{#if is_pointer}}\Pnlx\Types\PointerInterface{{/if}}|array{{#if cdata}}|\FFI\CData{{/if}}|null &${{name}}{{#if default_null}} = null{{/if}}{{else}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable|null{{/if}}{{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_pointer}}string|{{#if void_pointer}}\Pnlx\Types\String_|{{/if}}{{#if pointer_class}}{{pointer_class}}|{{/if}}\Pnlx\Types\PointerInterface|null{{/if}}{{#if cdata}}|\FFI\CData{{/if}} ${{name}}{{/if}}{{/if}}
{{~/inline~}}
{{#each functions}}if (!function_exists('{{fqn}}')) {
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('{{raw_name}}')]
    function {{name}}({{#each params}}{{> param}}{{#unless @last}}, {{/unless}}{{/each}}{{#if variadic}}{{#if params}}, {{/if}}mixed ...$__pnlx_varargs{{/if}}): {{#if is_void}}void{{else}}{{#if return_native}}{{return_native}}|{{/if}}{{return_class}}{{#if nullable_return}}|null{{/if}}{{/if}}
    {
{{#if has_out_params}}{{#if is_void}}        {{../entity_fqcn}}::{{name}}({{#each params}}${{name}}{{#unless @last}}, {{/unless}}{{/each}});
{{else}}        return {{../entity_fqcn}}::{{name}}({{#each params}}${{name}}{{#unless @last}}, {{/unless}}{{/each}});
{{/if}}{{else}}{{#if is_void}}        {{../entity_fqcn}}::{{name}}(...func_get_args());
{{else}}        return {{../entity_fqcn}}::{{name}}(...func_get_args());
{{/if}}{{/if}}    }
}

{{/each}}
