{{~#*inline "marshal_arg"~}}
{{#if is_pointer}}\Pnlx\FFI\ArgumentMarshaller::unwrap(${{name}}){{else}}\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, ${{name}}){{/if}}
{{~/inline~}}
{{~#*inline "dispatch"~}}
{{#if has_out_params}}\Pnlx\FFI\OutParameterMarshaller::call(static::class, __FUNCTION__, '{{call_name}}', [{{#each args}}{{#if is_native_pointer}}&${{name}}{{else}}{{> marshal_arg}}{{/if}}{{#unless @last}}, {{/unless}}{{/each}}]){{else}}static::__callStatic('{{call_name}}', {{#if variadic}}array_merge([{{#each args}}{{> marshal_arg}}{{#unless @last}}, {{/unless}}{{/each}}], $__pnlx_varargs){{else}}[{{#each args}}{{> marshal_arg}}{{#unless @last}}, {{/unless}}{{/each}}]{{/if}}){{/if}}
{{~/inline~}}
{{~#*inline "native_pointer_attr"~}}
#[\Pnlx\Attribute\NativePointer('{{np_element}}'{{#if np_string}}, string: true{{/if}}{{#if np_wrap}}, wrap: '{{np_wrap}}'{{/if}}{{#if np_buffer}}, buffer: true{{/if}})]
{{~/inline~}}
{{~#*inline "param"~}}
{{#if native_pointer}}{{> native_pointer_attr}} {{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable{{/if}}{{#if is_pointer}}\Pnlx\Types\PointerInterface{{/if}}|array{{#if cdata}}|\FFI\CData{{/if}}|null &${{name}}{{#if default_null}} = null{{/if}}{{else}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable|null{{/if}}{{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_pointer}}string|{{#if void_pointer}}\Pnlx\Types\String_|{{/if}}{{#if pointer_class}}{{pointer_class}}|{{/if}}\Pnlx\Types\PointerInterface|null{{/if}}{{#if cdata}}|\FFI\CData{{/if}} ${{name}}{{/if}}
{{~/inline~}}
{{~#*inline "return_type"~}}
{{#if is_void}}void{{/if}}{{#if is_string}}{{#if native_string}}string{{else}}\Pnlx\Types\String_{{/if}}{{/if}}{{#if cast}}{{cast}}{{/if}}{{#if new_class}}{{new_class}}|null{{/if}}
{{~/inline~}}
{{#each methods}}    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('{{raw_name}}')]
    public static function {{name}}({{#each params}}{{> param}}{{#unless @last}}, {{/unless}}{{/each}}{{#if variadic}}{{#if params}}, {{/if}}mixed ...$__pnlx_varargs{{/if}}): {{> return_type}}
    {
        static::__callStatic(static::PNLX_BOOT_TOKEN, []);
{{#if is_void}}        {{> dispatch}};
{{/if}}{{#if is_string}}{{#if native_string}}        return \Pnlx\Util::cString({{> dispatch}});
{{else}}        return new \Pnlx\Types\String_(\Pnlx\Util::cString({{> dispatch}}));
{{/if}}{{/if}}{{#if cast}}        return ({{cast}}) {{> dispatch}};
{{/if}}{{#if new_class}}        $__pnlx_ret = {{> dispatch}};
        return $__pnlx_ret === null ? null : new {{new_class}}($__pnlx_ret);
{{/if}}    }

{{/each}}
