{{~#*inline "marshal_arg"~}}
{{#if is_pointer}}\Pnlx\FFI\ArgumentMarshaller::unwrap(${{name}}){{else}}\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, ${{name}}){{/if}}
{{~/inline~}}
{{~#*inline "dispatch"~}}
{{#if has_out_params}}\Pnlx\FFI\OutParameterMarshaller::call(static::class, __FUNCTION__, '{{call_name}}', [{{#each args}}{{#if is_native_pointer}}&${{name}}{{else}}{{> marshal_arg}}{{/if}}{{#unless @last}}, {{/unless}}{{/each}}]){{else}}static::__callStatic('{{call_name}}', {{#if variadic}}array_merge([{{#each args}}{{> marshal_arg}}{{#unless @last}}, {{/unless}}{{/each}}], $__pnlx_varargs){{else}}[{{#each args}}{{> marshal_arg}}{{#unless @last}}, {{/unless}}{{/each}}]{{/if}}){{/if}}
{{~/inline~}}
{{~#*inline "native_pointer_attr"~}}
#[\Pnlx\Attribute\NativePointer('{{np_element}}'{{#if np_string}}, string: true{{/if}}{{#if np_wrap}}, wrap: '{{np_wrap}}'{{/if}}{{#if np_buffer}}, buffer: true{{/if}})]
{{~/inline~}}
{{~#*inline "param"~}}
{{#if callback}}callable{{#if cdata}}|\FFI\CData{{/if}}|null ${{name}}{{else}}{{#if native_pointer}}{{> native_pointer_attr}} {{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable{{/if}}{{#if is_pointer}}\Pnlx\Types\PointerInterface{{/if}}|array{{#if cdata}}|\FFI\CData{{/if}}|null &${{name}}{{#if default_null}} = null{{/if}}{{else}}{{#if enum_class}}{{enum_class}}|{{/if}}{{#if is_string}}string|\Pnlx\Types\String_|\Stringable|null{{/if}}{{#if is_int}}int|\Pnlx\Types\AnySizeInteger{{/if}}{{#if is_float}}float|int|\Pnlx\Types\AnyFloat{{/if}}{{#if is_pointer}}string|{{#if void_pointer}}\Pnlx\Types\String_|{{/if}}{{#if pointer_class}}{{pointer_class}}|{{/if}}\Pnlx\Types\PointerInterface|null{{/if}}{{#if cdata}}|\FFI\CData{{/if}} ${{name}}{{/if}}{{/if}}
{{~/inline~}}
{{~#*inline "return_type"~}}
{{#if enum_return}}{{enum_return}}|null{{else}}{{#if is_void}}void{{/if}}{{#if is_string}}{{#if native_string}}?string{{else}}\Pnlx\Types\String_|null{{/if}}{{/if}}{{#if cast}}{{cast}}{{/if}}{{#if new_class}}{{new_class}}|null{{/if}}{{/if}}
{{~/inline~}}
{{#each methods}}    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('{{raw_name}}')]
{{#if unsupported_attribute}}    #[{{unsupported_attribute}}]
{{/if}}    public static function {{name}}({{#each params}}{{> param}}{{#unless @last}}, {{/unless}}{{/each}}{{#if variadic}}{{#if params}}, {{/if}}mixed ...$__pnlx_varargs{{/if}}): {{> return_type}}
    {
{{#if unsupported_reason}}        throw new \Pnlx\Exception\UnsupportedNativeFunctionException(
            '{{raw_name}} is a C `{{unsupported_reason}}` function with no exported '
            . 'symbol, so it cannot be bound through FFI.'
        );
{{else}}        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
{{#if enum_return}}        return {{enum_return}}::tryFrom({{> dispatch}});
{{/if}}{{#if is_void}}        {{> dispatch}};
{{/if}}{{#if is_string}}{{#if native_string}}        return \Pnlx\Util::cStringOrNull({{> dispatch}});
{{else}}        $__pnlx_ret = \Pnlx\Util::cStringOrNull({{> dispatch}});
        return $__pnlx_ret === null ? null : new \Pnlx\Types\String_($__pnlx_ret);
{{/if}}{{/if}}{{#if cast}}        return ({{cast}}) {{> dispatch}};
{{/if}}{{#if new_class}}        $__pnlx_ret = {{> dispatch}};
        return $__pnlx_ret === null ? null : new {{new_class}}($__pnlx_ret);
{{/if}}{{/if}}    }

{{/each}}
