{{~#*inline "dispatch"~}}
static::__callStatic('{{call_name}}', [{{#each args}}{{#if is_pointer}}\Pnlx\FFI\ArgumentMarshaller::unwrap(${{name}}){{else}}\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, ${{name}}){{/if}}{{#unless @last}}, {{/unless}}{{/each}}])
{{~/inline~}}
{{#each methods}}    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('{{raw_name}}')]
    public static function {{name}}({{params}}): {{return_type}}
    {
{{#if is_void}}        {{> dispatch}};
{{/if}}{{#if is_string}}{{#if native_string}}        return \Pnlx\Util::cString({{> dispatch}});
{{else}}        return new \Pnlx\Helpers\String_(\Pnlx\Util::cString({{> dispatch}}));
{{/if}}{{/if}}{{#if cast}}        return ({{cast}}) {{> dispatch}};
{{/if}}{{#if new_class}}        return new {{new_class}}({{> dispatch}});
{{/if}}    }

{{/each}}
