<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * The method group of the example/example native library, as a reusable
 * trait. The {@see Example} entity `use`s it; a composed class can `use` several
 * such Component traits to expose all their functions through one shared FFI scope
 * (see {@see \Pnlx\Extension\AbstractExtension}). The `#[NativeLibraryComponent]`
 * attribute records the entity that carries this component's `#[NativeLibrary]`
 * metadata, so boot can resolve the cdef/library to load.
 */
#[\Pnlx\Attribute\NativeLibraryComponent(Example::class)]
#[\Pnlx\Attribute\AutoGeneratedByPnlx]
trait ExampleLibraryComponent
{
    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function exampleVersion(): \Pnlx\Types\String_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = \Pnlx\Util::cStringOrNull(static::__callStatic('exampleVersion', []));
        return $__pnlx_ret === null ? null : new \Pnlx\Types\String_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function example_version(): \Pnlx\Types\String_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = \Pnlx\Util::cStringOrNull(static::__callStatic('example_version', []));
        return $__pnlx_ret === null ? null : new \Pnlx\Types\String_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_next_mode')]
    public static function exampleNextMode(\Pnlx\Example\Enums\example_mode|int|\Pnlx\Types\AnySizeInteger|\FFI\CData $mode): \Pnlx\Example\Enums\example_mode|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        return \Pnlx\Example\Enums\example_mode::tryFrom(static::__callStatic('exampleNextMode', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $mode)]));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_next_mode')]
    public static function example_next_mode(\Pnlx\Example\Enums\example_mode|int|\Pnlx\Types\AnySizeInteger|\FFI\CData $mode): \Pnlx\Example\Enums\example_mode|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        return \Pnlx\Example\Enums\example_mode::tryFrom(static::__callStatic('example_next_mode', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $mode)]));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function exampleAdd(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $right): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('exampleAdd', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function example_add(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $left, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $right): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('example_add', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_apply')]
    public static function exampleApply(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $value, callable|\FFI\CData|null $callback): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('exampleApply', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $value), \Pnlx\FFI\ArgumentMarshaller::unwrap($callback)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_apply')]
    public static function example_apply(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $value, callable|\FFI\CData|null $callback): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('example_apply', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $value), \Pnlx\FFI\ArgumentMarshaller::unwrap($callback)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_sum')]
    public static function examplePointSum(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('examplePointSum', [\Pnlx\FFI\ArgumentMarshaller::unwrap($point)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_sum')]
    public static function example_point_sum(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point): \Pnlx\Types\Int_|null
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        $__pnlx_ret = static::__callStatic('example_point_sum', [\Pnlx\FFI\ArgumentMarshaller::unwrap($point)]);
        return $__pnlx_ret === null ? null : new \Pnlx\Types\Int_($__pnlx_ret);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_init')]
    public static function examplePointInit(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $x, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $y): void
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        static::__callStatic('examplePointInit', [\Pnlx\FFI\ArgumentMarshaller::unwrap($point), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $x), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $y)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_point_init')]
    public static function example_point_init(string|\Pnlx\Example\Types\example_point|\Pnlx\Types\PointerInterface|null|\FFI\CData $point, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $x, int|\Pnlx\Types\AnySizeInteger|\FFI\CData $y): void
    {
        \Pnlx\FFI\NativeLibraryRegistry::boot(static::class);
        static::__callStatic('example_point_init', [\Pnlx\FFI\ArgumentMarshaller::unwrap($point), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $x), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $y)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_inline_double')]
    #[\Pnlx\Attribute\StaticInline]
    public static function exampleInlineDouble(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $value): \Pnlx\Types\Int_|null
    {
        throw new \Pnlx\Exception\UnsupportedNativeFunctionException(
            'example_inline_double is a C `static inline` function with no exported '
            . 'symbol, so it cannot be bound through FFI.'
        );
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_inline_double')]
    #[\Pnlx\Attribute\StaticInline]
    public static function example_inline_double(int|\Pnlx\Types\AnySizeInteger|\FFI\CData $value): \Pnlx\Types\Int_|null
    {
        throw new \Pnlx\Exception\UnsupportedNativeFunctionException(
            'example_inline_double is a C `static inline` function with no exported '
            . 'symbol, so it cannot be bound through FFI.'
        );
    }


}
