<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * Per-C-type wrapper for a pointer this extension exposes. It extends the
 * package's base context wrapper, so it can be passed where a pointer is
 * accepted, and a returned pointer of this type arrives as this class. It is not
 * final: subclass it to add domain behaviour.
 */

namespace Pnlx\Example\Types;

/** Typed wrapper for a C `example_opaque` value. */
class example_opaque extends \Pnlx\Example\ExampleContext
{
    /**
     * extension が返した既存の `example_opaque` をラップする。
     * `\FFI\CData` がない場合は extension 自身の FFI スコープで `example_opaque[$size]` を確保し、
     * C API がポインタを要求する箇所へ `new example_opaque()` で完全な aggregate を渡せるようにする。
     */
    public function __construct(?\FFI\CData $cdata = null, int $size = 1)
    {
        if ($size < 1) {
            throw new \InvalidArgumentException('The allocation size must be at least 1.');
        }
        // 値で返された aggregate（`example_opaque *` ではなく `example_opaque` を返す関数など）は、
        // ポインタへ `reinterpret` cast できない。値を保持してアドレスを公開することで、
        // アクセサやポインタ利用では `example_opaque *` として扱い、値で再度渡すときは
        // デリファレンスする（ArgumentMarshaller::structValue を参照）。
        // PHP は union を TYPE_STRUCT と ATTR_UNION の組で表すため、両方をここで扱う。
        if ($cdata !== null && \FFI::typeof($cdata)->getKind() === \FFI\CType::TYPE_STRUCT) {
            $this->byValue = $cdata;
            parent::__construct(\FFI::addr($cdata));

            return;
        }
        if ($cdata === null) {
            $this->opaqueAllocation = \Pnlx\FFI\NativeLibraryRegistry::of(\Pnlx\Example\Example::class)
                ->allocateOpaque('example_opaque', 4, 4, $size);
            parent::__construct($this->opaqueAllocation->pointer());

            return;
        }
        parent::__construct(
            $cdata !== null
                ? \Pnlx\FFI\NativeLibraryRegistry::of(\Pnlx\Example\Example::class)->reinterpret('example_opaque', $cdata)
                : \Pnlx\FFI\NativeLibraryRegistry::of(\Pnlx\Example\Example::class)->allocate(sprintf('example_opaque[%d]', $size))
        );
    }

    /** 親へ渡したアドレスを有効に保つため、値渡しされた aggregate を保持する。 */
    private ?\FFI\CData $byValue = null;

    /** opaque な aggregate 用のアライン済み実体領域を保持する。 */
    private ?\Pnlx\FFI\OpaqueAllocation $opaqueAllocation = null;
}
