<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * Per-C-type wrapper for a pointer this extension exposes. It extends the
 * package's base context wrapper, so it can be passed where a pointer is
 * accepted, and a returned pointer of this type arrives as this class. It is not
 * final: subclass it to add domain behaviour.
 */

namespace Pnlx\Example\Types;

/** Typed wrapper for a C `example_point` value. */
class example_point extends \Pnlx\Example\ExampleContext
{
    /**
     * Wrap an existing `example_point` the extension returned, or — when no `\FFI\CData`
     * is given — allocate a fresh `example_point[$size]` in the extension's own FFI scope
     * (so a complete struct can be created with `new example_point()` and passed where the
     * C API wants a pointer to it).
     */
    public function __construct(?\FFI\CData $cdata = null, int $size = 1)
    {
        // A struct handed back BY VALUE (e.g. a function returning `example_point`, not
        // `example_point *`) can't be `reinterpret`-cast to a pointer. Keep it alive and
        // expose its address, so accessors and pointer uses see a `example_point *` while
        // by-value re-passing dereferences it (see ArgumentMarshaller::structValue).
        if ($cdata !== null && \FFI::typeof($cdata)->getKind() === \FFI\CType::TYPE_STRUCT) {
            $this->byValue = $cdata;
            parent::__construct(\FFI::addr($cdata));

            return;
        }
        parent::__construct(
            $cdata !== null
                ? \Pnlx\FFI\NativeLibraryRegistry::of(\Pnlx\Example\Example::class)->reinterpret('example_point', $cdata)
                : \Pnlx\FFI\NativeLibraryRegistry::of(\Pnlx\Example\Example::class)->allocate(sprintf('example_point[%d]', $size))
        );
    }

    /** Retains a by-value struct so the address handed to the parent stays valid. */
    private ?\FFI\CData $byValue = null;
    public function getX(): int
    {
        return $this->cdata()[0]->x;
    }

    public function setX(int $value): static
    {
        $this->cdata()[0]->x = $value;

        return $this;
    }

    public function getY(): int
    {
        return $this->cdata()[0]->y;
    }

    public function setY(int $value): static
    {
        $this->cdata()[0]->y = $value;

        return $this;
    }

}
