<?php

declare(strict_types=1);

namespace Pnlx\Tests\Support;

class RuntimeWorkspace
{
    public readonly string $projectRoot;

    public readonly string $packageSourceRoot;

    public readonly string $installedPackageRoot;

    public readonly string $nativeLibraryPath;

    private string $repoRoot;

    private function __construct()
    {
        $this->repoRoot = dirname(__DIR__, 2);
        $this->projectRoot = sys_get_temp_dir() . '/pnl-runtime-test-' . bin2hex(random_bytes(6));
        $this->packageSourceRoot = $this->projectRoot . '/packages/example';
        $this->installedPackageRoot = $this->projectRoot . '/@pnlx/packages/example/example/1.2.3';
        $this->nativeLibraryPath = $this->projectRoot . '/native/' . self::libraryName();
    }

    public static function create(): self
    {
        $workspace = new self();
        $workspace->copyPackageFixture();
        $workspace->compileNativeFixture();
        $workspace->writeProjectManifest();
        $workspace->installPackage();
        $workspace->writeGeneratedHooks();
        $workspace->installExtraPackage();
        $workspace->composeMembers();

        return $workspace;
    }

    /** The composite class generated by {@see composeMembers()}. */
    public const string COMPOSITE_CLASS = 'Pnlx\\Composed\\Demo';

    public function remove(): void
    {
        if (is_dir($this->projectRoot)) {
            Filesystem::removeDirectory($this->projectRoot);
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function pathmap(): array
    {
        return $this->readJson($this->projectRoot . '/@pnlx/pnlx-pathmap.json');
    }

    /**
     * @return array<string, mixed>
     */
    public function pnlManifest(): array
    {
        return $this->readJson($this->projectRoot . '/pnl.json');
    }

    /**
     * @return array<string, mixed>
     */
    public function lockExtension(string $name): array
    {
        $lock = $this->readJson($this->projectRoot . '/pnlx-lock.json');
        $extensions = $lock['extensions'] ?? null;
        $extension = is_array($extensions) ? ($extensions[$name] ?? null) : null;
        if (!is_array($extension)) {
            throw new \RuntimeException(sprintf('Extension %s is missing from the lockfile.', $name));
        }

        /** @var array<string, mixed> $extension */
        return $extension;
    }

    private function copyPackageFixture(): void
    {
        Filesystem::copyDirectory(
            $this->repoRoot . '/tests/fixtures/packages/example',
            $this->packageSourceRoot
        );

        mkdir($this->packageSourceRoot . '/src/generated', recursive: true);
        file_put_contents($this->packageSourceRoot . '/README.md', "example package\n");
        file_put_contents($this->packageSourceRoot . '/src/generated/stale.php', "<?php\n");
    }

    private function compileNativeFixture(): void
    {
        mkdir(dirname($this->nativeLibraryPath), recursive: true);
        $this->runner($this->projectRoot)->run([
            'rustc',
            '--crate-type',
            'cdylib',
            $this->repoRoot . '/tests/fixtures/native/example.rs',
            '-o',
            $this->nativeLibraryPath,
        ]);
    }

    private function writeProjectManifest(): void
    {
        $this->writeJson($this->projectRoot . '/pnl.json', [
            'schema_version' => '2026-07-01',
            'repositories' => [
                ['type' => 'file', 'url' => 'file://packages'],
            ],
            'library_paths' => [
                dirname($this->nativeLibraryPath),
            ],
            'features' => [
                'global_functions' => true,
                // Accept raw PHP scalars as arguments (tests pass plain ints); the
                // default wrapper-return entity variant is exercised.
                'scalar_params' => true,
            ],
            'extensions' => [
                'example/example' => ['version' => '=1.2.3', 'required' => true],
            ],
        ]);
    }

    private function installPackage(): void
    {
        $this->runner($this->projectRoot)->run([
            'cargo',
            'run',
            '--manifest-path',
            $this->repoRoot . '/Cargo.toml',
            '--bin',
            'pnl',
            '--',
            'install',
            'packages/example',
        ]);
    }

    /**
     * Install a second, distinct package (`extra`) so composition can be exercised.
     * Its native library lands beside the example one (both on `library_paths`).
     */
    private function installExtraPackage(): void
    {
        Filesystem::copyDirectory(
            $this->repoRoot . '/tests/fixtures/packages/extra',
            $this->projectRoot . '/packages/extra'
        );
        $this->runner($this->projectRoot)->run([
            'rustc',
            '--crate-type',
            'cdylib',
            $this->repoRoot . '/tests/fixtures/native/extra.rs',
            '-o',
            dirname($this->nativeLibraryPath) . '/' . self::extraLibraryName(),
        ]);
        $this->runner($this->projectRoot)->run([
            'cargo',
            'run',
            '--manifest-path',
            $this->repoRoot . '/Cargo.toml',
            '--bin',
            'pnl',
            '--',
            'install',
            'packages/extra',
        ]);
    }

    /** Fuse `example` + `extra` into one composite class via `pnl compose`. */
    private function composeMembers(): void
    {
        $this->runner($this->projectRoot)->run([
            'cargo',
            'run',
            '--manifest-path',
            $this->repoRoot . '/Cargo.toml',
            '--bin',
            'pnl',
            '--',
            'compose',
            'example',
            'extra',
            '--as',
            self::COMPOSITE_CLASS,
        ]);
    }

    private static function extraLibraryName(): string
    {
        return match (PHP_OS_FAMILY) {
            'Darwin' => 'libextra.dylib',
            'Windows' => 'extra.dll',
            default => 'libextra.so',
        };
    }

    private function writeGeneratedHooks(): void
    {
        $generatedRoot = $this->installedPackageRoot . '/src/generated';
        // Hooks run inside index.php after the static entity has been required, so
        // they can observe its `#[NativeLibrary]` metadata attribute.
        file_put_contents($generatedRoot . '/preload.php', <<<'PHP'
<?php

$GLOBALS['pnlx_test_preload_ran'] = true;
$GLOBALS['pnlx_test_preload_entity_booted'] = \Pnlx\FFI\NativeLibraryRegistry::info(\Pnlx\Example\Example::class)->name === 'example/example';
PHP);
        file_put_contents($generatedRoot . '/postload.php', <<<'PHP'
<?php

$GLOBALS['pnlx_test_postload_ran'] = true;
$GLOBALS['pnlx_test_postload_entity_booted'] = \Pnlx\FFI\NativeLibraryRegistry::info(\Pnlx\Example\Example::class)->name === 'example/example';
PHP);
    }

    private function runner(string $cwd): CommandRunner
    {
        return new CommandRunner($cwd);
    }

    /**
     * @param array<string, mixed> $data
     */
    private function writeJson(string $path, array $data): void
    {
        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), recursive: true);
        }

        file_put_contents($path, json_encode($data, JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR));
    }

    /**
     * @return array<string, mixed>
     */
    private function readJson(string $path): array
    {
        $data = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);
        if (!is_array($data)) {
            throw new \RuntimeException(sprintf('%s did not contain a JSON object.', $path));
        }

        /** @var array<string, mixed> $data */
        return $data;
    }

    private static function libraryName(): string
    {
        return match (PHP_OS_FAMILY) {
            'Darwin' => 'libexample.dylib',
            'Windows' => 'example.dll',
            default => 'libexample.so',
        };
    }
}
