<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 */

namespace Pnlx\Example;

/**
 * Generated entrypoint for the example/example native library.
 *
 * A C library is a bag of functions, so call this entity statically and never
 * instantiate it: `Example::some_c_function(...)`. All the wiring lives in the
 * shared {@see \Pnlx\Extension\AbstractExtension} base behind the magic
 * `__callStatic`, so this class holds ONLY the methods named after C functions
 * (plus the metadata constants) and nothing here can be shadowed by one.
 *
 * Metadata is install-time information baked in as constants: `Example::NAME`,
 * `VERSION`, `HASH`, `DESCRIPTION`, `PATH`. `HASH`/`PATH` describe the resolved
 * native library.
 */
#[\Pnlx\Attribute\NativeLibraryName('example/example')]
#[\Pnlx\Attribute\NativeLibraryVersion('1.2.3')]
#[\Pnlx\Attribute\AutoGeneratedByPnlx]
class Example extends \Pnlx\Extension\AbstractExtension
{
    protected const string FFI_FILE = 'example.ffi.php';

    protected const string PNLX_BOOT_TOKEN = '<normalized>';

    public const string NAME = 'example/example';

    public const string VERSION = '1.2.3';

    public const string DESCRIPTION = 'Test fixture native library.';

    // The resolved native library path and content hash, stamped in at install time.
    public const string PATH = '<normalized>';

    public const string HASH = '<normalized>';

    // Extra shared libraries co-loaded alongside this one (the package's
    // `dependencies` `library_names`), as absolute paths stamped in at install time.
    public const array LIBRARIES = [];

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function exampleVersion(): ?string
    {
        static::__callStatic(static::PNLX_BOOT_TOKEN, []);
        return \Pnlx\Util::cStringOrNull(static::__callStatic('exampleVersion', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_version')]
    public static function example_version(): ?string
    {
        static::__callStatic(static::PNLX_BOOT_TOKEN, []);
        return \Pnlx\Util::cStringOrNull(static::__callStatic('example_version', []));
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function exampleAdd(int|\Pnlx\Types\AnySizeInteger $left, int|\Pnlx\Types\AnySizeInteger $right): int
    {
        static::__callStatic(static::PNLX_BOOT_TOKEN, []);
        return (int) static::__callStatic('exampleAdd', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_add')]
    public static function example_add(int|\Pnlx\Types\AnySizeInteger $left, int|\Pnlx\Types\AnySizeInteger $right): int
    {
        static::__callStatic(static::PNLX_BOOT_TOKEN, []);
        return (int) static::__callStatic('example_add', [\Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $left), \Pnlx\FFI\ArgumentMarshaller::scalarArg(static::class, $right)]);
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_inline_double')]
    #[\Pnlx\Attribute\StaticInline]
    public static function exampleInlineDouble(int|\Pnlx\Types\AnySizeInteger $value): int
    {
        throw new \Pnlx\Exception\UnsupportedNativeFunctionException(
            'example_inline_double is a C `static inline` function with no exported '
            . 'symbol, so it cannot be bound through FFI.'
        );
    }

    #[\Pnlx\Attribute\AutoGeneratedByPnlx]
    #[\Pnlx\Attribute\RawNativeName('example_inline_double')]
    #[\Pnlx\Attribute\StaticInline]
    public static function example_inline_double(int|\Pnlx\Types\AnySizeInteger $value): int
    {
        throw new \Pnlx\Exception\UnsupportedNativeFunctionException(
            'example_inline_double is a C `static inline` function with no exported '
            . 'symbol, so it cannot be bound through FFI.'
        );
    }


}
