typedef signed long ssize_t;
typedef unsigned long size_t;
typedef long intptr_t;
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef unsigned char Uint8;
typedef unsigned short Uint16;
typedef unsigned int Uint32;
