<?php

declare(strict_types=1);

/*
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * This file was generated automatically by a machine, so any changes you make to
 * it may be overwritten the next time it is regenerated.
 * If you want to change its behavior, extend or call the classes and functions
 * declared in this generated file instead.
 * The authors accept no responsibility for anything that results from using this
 * generated file, and managing it in a version control system such as git or svn
 * is not recommended.
 *
 * Generated at: <normalized>
 * Generated on: <normalized>
 * Generator OS: <normalized>
 * PHP version: <normalized>
 *
 * A native C `enum example_mode`, surfaced as an int-backed PHP enum. Pass a case
 * where this enum is accepted (its backing `->value` is sent to C); a returned
 * value is mapped back with `example_mode::tryFrom()`, yielding `null` for a value
 * the C API returned that is outside the enum.
 */

namespace Pnlx\Example\Enums;

enum example_mode: int
{
    case EXAMPLE_MODE_OFF = 0;
    case EXAMPLE_MODE_ON = 1;
    case EXAMPLE_MODE_AUTO = 10;
}
